/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inscada.migrator;

/**
 *
 * @author fadime
 */
public class AppTable extends javax.swing.JFrame {

    private MigratorImpl migratorImpl;

    public MigratorImpl getMigratorImpl() {
        return migratorImpl;
    }

    public void setMigratorImpl(MigratorImpl migratorImpl) {
        this.migratorImpl = migratorImpl;
    }
    /**
     * Creates new form AppTable
     */
    public AppTable() {
        initComponents();
        setSize(600,355);
        setLocation((WIDTH+700)/2,(HEIGHT+200)/2 );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        event_log = new javax.swing.JRadioButton();
        fired_alarm = new javax.swing.JRadioButton();
        read_variable_values = new javax.swing.JRadioButton();
        transfer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 340));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));

        event_log.setBackground(new java.awt.Color(36, 47, 65));
        event_log.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        event_log.setText(" EVENT LOG");

        fired_alarm.setBackground(new java.awt.Color(36, 47, 65));
        fired_alarm.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        fired_alarm.setText(" FİRED ALARM");

        read_variable_values.setBackground(new java.awt.Color(36, 47, 65));
        read_variable_values.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        read_variable_values.setText(" READ VARIABLE VALUES");

        transfer.setBackground(new java.awt.Color(102, 102, 102));
        transfer.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        transfer.setForeground(new java.awt.Color(204, 204, 204));
        transfer.setText("TRANSFER");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(read_variable_values)
                            .addComponent(fired_alarm)
                            .addComponent(event_log)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(event_log)
                .addGap(27, 27, 27)
                .addComponent(fired_alarm)
                .addGap(29, 29, 29)
                .addComponent(read_variable_values)
                .addGap(37, 37, 37)
                .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 410, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        if(event_log.isSelected()){
            getMigratorImpl().transferEventLogs();
        }
        if(fired_alarm.isSelected()){
            getMigratorImpl().transferFiredAlarms();
        }
        if (read_variable_values.isSelected()) {
            getMigratorImpl().transferVariableValues();
            
        }
        if(!event_log.isSelected() && !fired_alarm.isSelected() && !read_variable_values.isSelected()){
            System.out.println("PLEASE SELECT TABLE");
        }
    }//GEN-LAST:event_transferActionPerformed

    /**
     * @param args the command line arguments
     */
    void Allconnections(MigratorImpl migratorImpl){
        setMigratorImpl(migratorImpl);
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton event_log;
    private javax.swing.JRadioButton fired_alarm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton read_variable_values;
    private javax.swing.JButton transfer;
    // End of variables declaration//GEN-END:variables

    
}
